kind: pipeline
type: docker
name: default1

steps:
- name: test/build
  image: golang
  commands:
  - go test
  - go build
  
trigger:
  branch:
  - master
platform:
  os: linux
  arch: amd64
workspace:
  path: /opt/src