kind: pipeline
type: docker
name: default
workspace:
  path: /opt/src
steps:
  - name: build
    image: golang
    commands:
    - go test
    - go build

  - name: push
    image: plugins/docker
    pull: if-not-exists
    settings:
      username:
        from_secret: harbor_username
      password:
        from_secret: harbor_password
      dockerfile: Dockerfile
      repo: registry.cn-hangzhou.aliyuncs.com/lijincheng/cocoballli
      registry: registry.cn-hangzhou.aliyuncs.com