kind: pipeline
type: docker
name: default
workspace:
  path: /opt/src
steps:
  - name: build
    image: golang
    commands:
    - go test
    - go build

  - name: push
    image: plugins/docker
    pull: if-not-exists
    settings:
      username:
        from_secret: cocoball
      password:
        from_secret: ljcloveyou99
      repo: cocoball/lijincheng:tagname
      registry: https://hub.docker.com
      dockerfile: Dockerfile
      mirror: https://hub.docker.com
  
# kind: pipeline
# type: docker
# name: default
# steps:
# - name: busybox
#   image: busybox
#   commands:
#   - env
