kind: pipeline
type: docker
name: default

steps:
- name: backend
  image: golang
  commands:
  - go build main.go 
  - ./mian 

trigger:
  branch:
  - master
platform:
  os: linux
  arch: amd64
workspace:
  path: /opt/src