kind: pipeline
type: docker
name: default




workspace:
  path: /opt/src

steps:
  - name: test/build
    image: golang
    commands:
    - go test
    - go build
    - go run drone 
  
# kind: pipeline
# type: docker
# name: default
# steps:
# - name: busybox
#   image: busybox
#   commands:
#   - env
